create extension if not exists pgcrypto;

create table if not exists public.products (
  id text primary key,
  name text not null,
  sku text,
  price_paise integer not null check (price_paise >= 0),
  sale_price_paise integer,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  low_stock_threshold integer not null default 5 check (low_stock_threshold >= 0),
  category text,
  image_url text,
  variants jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  inventory_deducted_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

insert into public.products (id, name, price_paise, category, image_url)
values
  ('pure-organic-a2-gir-cow-ghee', 'Pure Organic A2 Gir Cow Bilona Ghee', 130000, 'ghee', '/images/products/gir-govalan-ghee-jar.png'),
  ('a2-gir-milk', 'A2 Gir Cow Milk', 84000, 'dairy', '/images/products/a2-gir-milk.jpg'),
  ('fresh-curd', 'Fresh Curd', 15000, 'dairy', '/images/products/fresh-curd.jpg'),
  ('traditional-ladoo', 'Traditional Ladoo', 34900, 'sweets', '/images/products/traditional-ladoo.jpg'),
  ('milk-peda', 'Milk Peda', 65000, 'sweets', '/images/products/milk-peda.jpg'),
  ('shrikhand', 'Shrikhand', 29900, 'sweets', '/images/products/shrikhand.jpg')
on conflict (id) do nothing;

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  discount_value integer not null check (discount_value > 0),
  minimum_order_paise integer not null default 0 check (minimum_order_paise >= 0),
  maximum_discount_paise integer,
  starts_at timestamptz,
  expires_at timestamptz,
  usage_limit integer,
  usage_count integer not null default 0,
  one_per_customer boolean not null default false,
  product_ids jsonb not null default '[]'::jsonb,
  categories jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists coupons_code_idx on public.coupons (code);
alter table public.coupons enable row level security;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text unique not null,
  email text,
  address text,
  city text,
  state text,
  pincode text,
  country text not null default 'India',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customers_name_idx on public.customers (name);
create index if not exists customers_email_idx on public.customers (email);
alter table public.customers enable row level security;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  razorpay_order_id text unique not null,
  razorpay_payment_id text unique,
  customer_id uuid references public.customers(id),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  address text not null,
  landmark text,
  city text not null,
  state text not null,
  pincode text not null,
  items jsonb not null,
  amount_paise integer not null check (amount_paise > 0),
  currency text not null default 'INR',
  payment_status text not null default 'created' check (payment_status in ('created', 'paid', 'failed', 'refunded', 'partially_refunded')),
  order_status text not null default 'new' check (order_status in ('new', 'processing', 'shipped', 'delivered', 'cancelled')),
  tracking_number text,
  shipping_partner text,
  notes text,
  coupon_code text,
  discount_paise integer not null default 0,
  inventory_deducted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists customer_id uuid references public.customers(id);

insert into public.customers (name, phone, email, address, city, state, pincode)
select distinct on (customer_phone)
  customer_name, customer_phone, customer_email, address, city, state, pincode
from public.orders
where customer_phone is not null and customer_phone <> ''
on conflict (phone) do nothing;

update public.orders orders
set customer_id = customers.id
from public.customers customers
where orders.customer_id is null and orders.customer_phone = customers.phone;

create index if not exists orders_status_idx on public.orders (order_status, created_at desc);
create index if not exists orders_payment_status_idx on public.orders (payment_status, created_at desc);

create or replace function public.set_coupon_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists coupons_updated_at on public.coupons;
create trigger coupons_updated_at before update on public.coupons
for each row execute function public.set_coupon_updated_at();

create or replace function public.set_customer_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists customers_updated_at on public.customers;
create trigger customers_updated_at before update on public.customers
for each row execute function public.set_customer_updated_at();

alter table public.orders enable row level security;
alter table public.orders add column if not exists coupon_code text;
alter table public.orders add column if not exists discount_paise integer not null default 0;
alter table public.orders add column if not exists inventory_deducted boolean not null default false;

create or replace function public.fulfill_paid_order(order_id_input uuid)
returns void language plpgsql security definer as $$
declare
  order_row public.orders%rowtype;
  item jsonb;
  product_row public.products%rowtype;
  quantity integer;
begin
  select * into order_row from public.orders where id = order_id_input for update;
  if not found or order_row.inventory_deducted or order_row.payment_status <> 'paid' then return; end if;
  for item in select * from jsonb_array_elements(order_row.items) loop
    quantity := greatest(1, least(99, coalesce((item->>'qty')::integer, 1)));
    select * into product_row from public.products where id = item->>'productId' for update;
    if not found or not product_row.active or product_row.stock_quantity < quantity then
      raise exception 'Insufficient stock for product %', item->>'productId';
    end if;
    update public.products set stock_quantity = stock_quantity - quantity, inventory_deducted_count = inventory_deducted_count + quantity where id = product_row.id;
  end loop;
  update public.orders set inventory_deducted = true where id = order_id_input;
end;
$$;

create or replace function public.redeem_coupon(coupon_code_input text)
returns void language plpgsql security definer as $$
begin
  update public.coupons
  set usage_count = usage_count + 1
  where code = upper(trim(coupon_code_input))
    and active = true
    and (usage_limit is null or usage_count < usage_limit);
  if not found then raise exception 'Coupon usage limit reached or coupon is inactive.'; end if;
end;
$$;

create or replace function public.set_order_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders
for each row execute function public.set_order_updated_at();