create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  razorpay_order_id text unique not null,
  razorpay_payment_id text unique,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  address text not null,
  landmark text,
  city text not null,
  state text not null,
  pincode text not null,
  items jsonb not null,
  amount_paise integer not null check (amount_paise > 0),
  currency text not null default 'INR',
  payment_status text not null default 'created' check (payment_status in ('created', 'paid', 'failed', 'refunded', 'partially_refunded')),
  order_status text not null default 'new' check (order_status in ('new', 'processing', 'shipped', 'delivered', 'cancelled')),
  tracking_number text,
  shipping_partner text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_status_idx on public.orders (order_status, created_at desc);
create index if not exists orders_payment_status_idx on public.orders (payment_status, created_at desc);

alter table public.orders enable row level security;

create or replace function public.set_order_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders
for each row execute function public.set_order_updated_at();