create extension if not exists pgcrypto;

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  discount_value integer not null check (discount_value > 0),
  minimum_order_paise integer not null default 0 check (minimum_order_paise >= 0),
  maximum_discount_paise integer,
  starts_at timestamptz,
  expires_at timestamptz,
  usage_limit integer,
  usage_count integer not null default 0,
  one_per_customer boolean not null default false,
  product_ids jsonb not null default '[]'::jsonb,
  categories jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists coupons_code_idx on public.coupons (code);
alter table public.coupons enable row level security;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text unique not null,
  email text,
  address text,
  city text,
  state text,
  pincode text,
  country text not null default 'India',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customers_name_idx on public.customers (name);
create index if not exists customers_email_idx on public.customers (email);
alter table public.customers enable row level security;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  razorpay_order_id text unique not null,
  razorpay_payment_id text unique,
  customer_id uuid references public.customers(id),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  address text not null,
  landmark text,
  city text not null,
  state text not null,
  pincode text not null,
  items jsonb not null,
  amount_paise integer not null check (amount_paise > 0),
  currency text not null default 'INR',
  payment_status text not null default 'created' check (payment_status in ('created', 'paid', 'failed', 'refunded', 'partially_refunded')),
  order_status text not null default 'new' check (order_status in ('new', 'processing', 'shipped', 'delivered', 'cancelled')),
  tracking_number text,
  shipping_partner text,
  notes text,
  coupon_code text,
  discount_paise integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists customer_id uuid references public.customers(id);

insert into public.customers (name, phone, email, address, city, state, pincode)
select distinct on (customer_phone)
  customer_name, customer_phone, customer_email, address, city, state, pincode
from public.orders
where customer_phone is not null and customer_phone <> ''
on conflict (phone) do nothing;

update public.orders orders
set customer_id = customers.id
from public.customers customers
where orders.customer_id is null and orders.customer_phone = customers.phone;

create index if not exists orders_status_idx on public.orders (order_status, created_at desc);
create index if not exists orders_payment_status_idx on public.orders (payment_status, created_at desc);

create or replace function public.set_coupon_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists coupons_updated_at on public.coupons;
create trigger coupons_updated_at before update on public.coupons
for each row execute function public.set_coupon_updated_at();

create or replace function public.set_customer_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists customers_updated_at on public.customers;
create trigger customers_updated_at before update on public.customers
for each row execute function public.set_customer_updated_at();

alter table public.orders enable row level security;
alter table public.orders add column if not exists coupon_code text;
alter table public.orders add column if not exists discount_paise integer not null default 0;

create or replace function public.redeem_coupon(coupon_code_input text)
returns void language plpgsql security definer as $$
begin
  update public.coupons
  set usage_count = usage_count + 1
  where code = upper(trim(coupon_code_input))
    and active = true
    and (usage_limit is null or usage_count < usage_limit);
  if not found then raise exception 'Coupon usage limit reached or coupon is inactive.'; end if;
end;
$$;

create or replace function public.set_order_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders
for each row execute function public.set_order_updated_at();